# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[github-actions] " (no colon, but a trailing whitespace)
      prefix: "[github-actions] "
    labels:
      - "github-actions"
      - "dependencies"
    assignees:
      - "chrisloarryn"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "[npm] "
    labels:
      - "npm"
      - "dependencies"
    assignees:
      - "chrisloarryn"
    
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[docker] "
    labels:
      - "docker"
      - "dependencies"
    assignees:
      - "chrisloarryn"
