image: node:25.8.0

stages:
  - build
  - test
  - deploy

before_script:
  - corepack enable
  - yarn install --frozen-lockfile

build:
  stage: build
  script:
    - yarn lint
    - yarn build
  cache:
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
    - yarn coverage
    - yarn test:e2e
  cache:
    paths:
      - coverage/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml
      codequality:
        - cobertura-coverage.xml

deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r coverage/* .public
    - mv .public public
  dependencies:
    - test
  artifacts:
    paths:
      - public
  only:
    - master
    - qa
    - dev
  except:
    - tags
