version: "3"
services:
  service:
    restart: always
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:4000"
    volumes:
      - ./data/app:/app
      - ./data/root:/root
      - ./node_modules:/app/node_modules
      # /tmp
      - ./data/tmp:/tmp
      - ./data/:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - "NODE_ENV=development"
      - "PORT=3000"
      - "PROD_NODE_MODULES_PATH=/tmp/prod_node_modules"
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
